---
# user
- name: Create user {{ myblog_user }}
  user: name="{{ myblog_user }}" shell=/bin/bash home="{{ myblog_home }}"

- name: Add my public key to {{ myblog_user }}
  authorized_key: user={{ myblog_user }}
                  key="{{ lookup('file', ssh_public_key_file) }}"

# myblog
- name: Install requirements
  apt: name={{ item }} state=present
  with_items:
    - python
    - python-dev
    - python-setuptools
    - build-essential
    - libmysqlclient-dev

- name: Install pip
  easy_install: name=pip

- name: Install virtualenv
  pip: name=virtualenv

- name: Install MySQL-python
  pip: name=MySQL-python virtualenv="{{ myblog_venv }}"
  remote_user: "{{ myblog_user }}"

- name: Git pull blog
  git: repo=https://github.com/ZuluPro/myblog.git
       dest=/tmp/src/myblog version={{ myblog_version }}
  remote_user: "{{ myblog_user }}"

- name: Install myblog requirements
  pip: requirements=/tmp/src/myblog/requirements.txt
       virtualenv="{{ myblog_venv }}"
  remote_user: "{{ myblog_user }}"

- name: Install myblog
  shell: "{{ myblog_venv }}/bin/python setup.py install"
  args:
     chdir: /tmp/src/myblog
  remote_user: "{{ myblog_user }}"

- name: Get package directory
  shell: myblog settings | awk '/BASE_DIR/ {print $3}'
  remote_user: "{{ myblog_user }}"
  register: myblog_basedir
  environment:
    PATH: "{{ myblog_venv }}/bin/:{{ ansible_env.PATH }}"

- name: Setup myblog configuration
  template: src=myblog.cfg.j2 dest=/etc/myblog.cfg mode=0644 owner=root

- name: Deploy static files
  command: "{{ myblog_venv }}/bin/python manage.py collectstatic --noinput"
  args:
     chdir: /tmp/src/myblog/myblog
  remote_user: "{{ myblog_user }}"

- name: Deploy database 
  command: "{{ myblog_venv }}/bin/python manage.py migrate --noinput"
  args:
     chdir: /tmp/src/myblog/myblog
  remote_user: "{{ myblog_user }}"

# uWSGI
- name: Install uWSGI
  apt: name={{ item }} state=latest
  with_items:
    - uwsgi
    - uwsgi-plugin-python

- name: Setup myblog uWSGI configuration
  template: src=uwsgi.ini.j2 dest=/etc/uwsgi/apps-available/myblog.ini
  notify: restart uwsgi

- name: Enable myblog uWSGI configuration
  file: src=/etc/uwsgi/apps-available/myblog.ini dest=/etc/uwsgi/apps-enabled/myblog.ini state=link
