#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

# GETTING-STARTED: change 'db.sqlite3' to your sqlite3 database:
echo "Executing 'python $OPENSHIFT_REPO_DIR/myblog/manage.py migrate --noinput'"
python "$OPENSHIFT_REPO_DIR"/myblog/manage.py migrate --noinput

# GETTING-STARTED: change 'myproject' to your project name:
echo "Executing 'python $OPENSHIFT_REPO_DIR/myblog/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"/myblog/manage.py collectstatic --noinput
