language: python

env:
  - DJANGO="1.7" DB="sqlite"

install:
  - sudo apt-get install python-setuptools python-dev gcc
  - sudo easy_install pip
  - sudo pip install tox
  - TOX_ENV=py2.7-django${DJANGO}-${DB}
  - tox -e $TOX_ENV --notest
  - cp extras/travis/myblog-${DB}.cfg ~/.myblog.cfg
  - extras/travis/before-install-${DB}.sh
  - extras/travis/before-install-common.sh

script: tox -e $TOX_ENV
