language: python
services: mysql
python:
  # - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "pypy"

env:
  global:
    - secure: R2OC8k1XEHR+wUXcCMBLcxNxcas429I0PvYUr8V/JYpnmMF1qhJDXBgZATdV91TCl+QxBGc0Me1sxUiGV3t4lSmcO3D7TG+omZ/vUykLka5UPwD/tX7vt7I3zGz20Sk7hB2RR/vlAWmUOjmQTxkQ2ihUKcosh5z9ZRRnJHqfpgM=
    - secure: atuOq8sV91onfYOJAPlnPAJeZML/Ji7/1Q+mL8lUBD7VpIO95HV+3ZSXbmUuiNI72TDFelheps9mxoEBZNpAZNXAzb7X9/Bgwjw0W1lhZtm/FFgUEKPqPKafLj7+5cEJBna+5azdlLOiR2CVKWvNglPwNeqY1EZbh6CxGSiBSQo=
  # matrix:
  #   - DJANGO="1.7" DB="sqlite"
  #   - DJANGO="1.7" DB="mysql"
  #   - DJANGO="1.7" DB="postgresql"
  #   - DJANGO="1.8" DB="sqlite"
  #   - DJANGO="1.8" DB="mysql"
  #   - DJANGO="1.8" DB="postgresql"

install:
  - TOX_ENV=py${TRAVIS_PYTHON_VERSION}-django${DJANGO}-${DB}
  - pip install tox coveralls codecov
  - tox -e $TOX_ENV --notest
  - cp extras/travis/myblog-${DB}.cfg ~/.myblog.cfg
  - extras/travis/before-install-${DB}.sh
  - extras/travis/before-install-common.sh

script: tox -e $TOX_ENV
after_success:
  - tox -e $TOX_ENV -- coveralls $COVERALLS_OPTION
  - tox -e $TOX_ENV -- codecov

matrix:
  fast_finish: true
  allow_failures:
    # Zinnia 0.15 doesn't support Django 1.8
    - python: "2.7"
      env: DJANGO="1.8" DB="postgresql" 
  exclude:
    # Python 3
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    # Get pure Python driver
    - python: "pypy"
      env: DJANGO="1.7" DB="postgresql" 
    - python: "pypy"
      env: DJANGO="1.8" DB="postgresql" 
  include:
    - python: "2.7"
      env: ANSIBLE=
      install: sudo pip install ansible
      script:
        - cd extras/ansible
        - cp ../travis/ansible-vars.yml vars.yml
        - sudo ansible-playbook main.yml -i ../travis/ansible-hosts -vv

# addons:
#   sauce_connect: true
