database:
  image: mariadb
  volumes:
    - /opt/mysql:/var/lib/mysql:rw
    - extras/docker-compose/my.cnf:/etc/mysql/my.cnf:ro
  env_file: extras/docker-compose/compose.env

cache:
  image: redis

static:
  build: .
  entrypoint: 
  command: myblog collectstatic --noinput
  volumes:
    - extras/docker-compose/myblog.cfg:/myblog.cfg:ro
    - static
  environment:
    - BLOG_CONFIG_FILE=/myblog.cfg
  
middleware:
  build: .
  command: uwsgi --ini /uwsgi.ini
  links:
    - database
    - cache
  volumes:
    - extras/docker-compose/myblog.cfg:/myblog.cfg:ro
    - media

frontend:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - extras/docker-compose/nginx_site.conf:/etc/nginx/conf.d/default.conf:ro
    - extras/docker-compose/nginx_media.conf:/etc/nginx/conf.d/media.conf:ro
    - extras/docker-compose/ssl-certs:/ssl/:ro
  volumes_from:
    - static
    - middleware
  links:
    - middleware
