database:
  image: mariadb
  volumes:
    - /opt/mysql:/var/lib/mysql:rw
    - extras/docker-compose/my.cnf:/etc/mysql/my.cnf:ro
  env_file: extras/docker-compose/compose.env

cache:
  image: redis

static:
  build: .
  command: myblog collectstatic --noinput
  
middleware:
  build: .
  command: uwsgi --ini /tmp/uwsgi.ini
  links:
    - database
    - cache
  volumes_from:
    - static

frontend:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - extras/docker-compose/nginx_site.conf:/etc/nginx/conf.d/default.conf:ro
    - extras/docker-compose/ssl-certs/myblog.crt:/etc/ssl/certs/myblog.crt:ro
    - extras/docker-compose/ssl-certs/myblog.key:/etc/ssl/private/myblog.key:ro
    - extras/docker-compose/ssl-certs/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
  volumes_from:
    - static
  links:
    - middleware
