---
- hosts: all
  vars_files:
    - vars.yml
  roles:
    - {role: common, tags: common}
    - {role: database, tags: database}
    - {role: cache, tags: cache}
    - {role: middleware, tags: middleware}
    - {role: frontend, tags: frontend}
