---
- name: Install MySQL
  apt: name={{ item }} state=latest
  with_items:
    - mariadb-server
    - python-mysqldb

- name: Start MariaDB
  action: service name=mysql state=started

- name: Configuring root user (if not made)
  mysql_user: name=root host={{ item }} password={{ root_db_password }} priv=*.*:ALL,GRANT
  with_items:
      - 127.0.0.1
      - ::1
      - localhost
  register: root_mysql_configuration
  ignore_errors: True

- name: Create root .my.cnf
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Create myblog database
  mysql_db: name=myblog state=present

- mysql_user: name=myblog host={{ item }} password={{ db_password }} priv=myblog.*:ALL state=present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
